### ISSUE TITLE
Exception due to wires not being integers

### ISSUE THREAD

**Issue by ycchen1989** [rigetti/pennylane-forest#32]
Hello all,

I tried to use the Forest plugin to run the circuit, my interface is Torch and the error message came out as:
When I use qiskit and default qubit, no issues at all. Wondering if this plugin is not yet compatible with Torch interface?

Thanks.
```
Traceback (most recent call last):
  File "minimumRunCode_shorter.py", line 122, in <module>
    main(batch_size = 10, epoch_num = 100, dev = dev)
  File "minimumRunCode_shorter.py", line 105, in main
    loss = cost(VQC = vqc, X = x_for_train, Y = y_for_train)
  File "minimumRunCode_shorter.py", line 82, in cost
    output = loss(torch.stack([VQC.forward(item) for item in X]), Y)
  File "minimumRunCode_shorter.py", line 82, in <listcomp>
    output = loss(torch.stack([VQC.forward(item) for item in X]), Y)
  File "minimumRunCode_shorter.py", line 73, in forward
    raw_output = self.circuit(angles)
  File "minimumRunCode_shorter.py", line 66, in circuit
    return _circuit(self.var_Q_circuit, angles = angles)
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pennylane/interfaces/torch.py", line 215, in custom_apply
    return _TorchQNode.apply(keyword_values, *args)
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pennylane/interfaces/torch.py", line 119, in forward
    res = qnode(*ctx.args, **ctx.kwargs)
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pennylane/qnode.py", line 606, in __call__
    return self.evaluate(args, **kwargs)  # args as one tuple
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pennylane/qnode.py", line 682, in evaluate
    ret = self.device.execute(self.circuit.operations, self.circuit.observables, self.variable_deps)
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pennylane/_device.py", line 171, in execute
    self.apply(operation.name, operation.wires, operation.parameters)
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pennylane_forest/device.py", line 228, in apply
    self.prog += self._operation_map[operation](*par, *wires)
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pyquil/gates.py", line 203, in RY
    return Gate(name="RY", params=[angle], qubits=[unpack_qubit(qubit)])
  File "/Users/ycchen/Desktop/Programming_Exercise/QISKIT_EXERCISE/PENNYLANE/PyTorchAcceleration/TorchPennyLane_ver7/lib/python3.7/site-packages/pyquil/quilatom.py", line 129, in unpack_qubit
    raise TypeError("qubit should be an int or Qubit or QubitPlaceholder instance")
TypeError: qubit should be an int or Qubit or QubitPlaceholder instance
```

the reproducing code
```python
import pennylane as qml
from pennylane import numpy as np

import matplotlib.pyplot as plt
from datetime import datetime

import torch
import torch.nn as nn 
from torch.autograd import Variable

dtype = torch.cuda.DoubleTensor if torch.cuda.is_available() else torch.DoubleTensor
device = 'cuda' if torch.cuda.is_available() else 'cpu'

###
class VQC:
	def __init__(
			self,
			num_of_input= 10,
			num_of_output= 2,
			num_of_wires = 10,
			var_Q_circuit = None,
			var_C_scaling = None,
			dev = None
			):

		self.var_Q_circuit = var_Q_circuit
		self.var_C_scaling = var_C_scaling
		self.num_of_input = num_of_input
		self.num_of_output = num_of_output
		self.num_of_wires = num_of_wires
		self.dev = dev

	def _layer(self, W):

		qml.CNOT(wires=[0, 1])
		qml.CNOT(wires=[1, 2])
		qml.CNOT(wires=[2, 3])
		qml.CNOT(wires=[3, 4])
		qml.CNOT(wires=[4, 5])
		qml.CNOT(wires=[5, 6])
		qml.CNOT(wires=[6, 7])
		qml.CNOT(wires=[7, 8])
		qml.CNOT(wires=[8, 9])
		qml.CNOT(wires=[9, 0])


		qml.Rot(W[0, 0], W[0, 1], W[0, 2], wires=0)
		qml.Rot(W[1, 0], W[1, 1], W[1, 2], wires=1)
		qml.Rot(W[2, 0], W[2, 1], W[2, 2], wires=2)
		qml.Rot(W[3, 0], W[3, 1], W[3, 2], wires=3)
		qml.Rot(W[4, 0], W[4, 1], W[4, 2], wires=4)
		qml.Rot(W[5, 0], W[5, 1], W[5, 2], wires=5)
		qml.Rot(W[6, 0], W[6, 1], W[6, 2], wires=6)
		qml.Rot(W[7, 0], W[7, 1], W[7, 2], wires=7)
		qml.Rot(W[8, 0], W[8, 1], W[8, 2], wires=8)
		qml.Rot(W[9, 0], W[9, 1], W[9, 2], wires=9)

	def circuit(self, angles):
		@qml.qnode(self.dev, interface='torch')
		def _circuit(var_Q_circuit, angles = None):
			qml.templates.embeddings.AmplitudeEmbedding(angles, wires=list(range(self.num_of_wires)))
			weights = var_Q_circuit
			for W in weights:
				self._layer(W)
			return [qml.expval(qml.PauliZ(k)) for k in range(self.num_of_output)]
		return _circuit(self.var_Q_circuit, angles = angles)

	def forward(self, angles):
		print(angles)
		angles = self.var_C_scaling * angles
		print(angles)
		angles = angles / torch.clamp(torch.sqrt(torch.sum(angles ** 2)), min = 1e-9)
		raw_output = self.circuit(angles)
		m = nn.Softmax(dim=0)
		clamp = 1e-9 * torch.ones(self.num_of_output).type(dtype).to(device)
		normalized_output = torch.max(raw_output, clamp)
		output = m(normalized_output)
		return output

def cost(VQC, X, Y):
	loss = nn.CrossEntropyLoss()
	output = loss(torch.stack([VQC.forward(item) for item in X]), Y)
	print("LOSS AVG: ",output)
	return output

def main(batch_size, epoch_num, dev):
	num_of_input = 10
	num_of_output = 2
	num_layers = 4
	num_qubits = 10
	var_C_scaling = Variable(torch.ones(1024, dtype = torch.double), requires_grad=True)
	var_Q_circuit = Variable(torch.tensor(0.01 * np.random.randn(num_layers, num_qubits, 3), device=device).type(dtype), requires_grad=True)
	vqc = VQC(num_of_input = num_of_input, num_of_output = num_of_output, num_of_wires = num_qubits, var_Q_circuit = var_Q_circuit, var_C_scaling = var_C_scaling, dev= dev)

	params = [var_C_scaling, var_Q_circuit]

	opt = torch.optim.RMSprop(params, lr=0.01, alpha=0.99, eps=1e-08, weight_decay=0, momentum=0, centered=False)

	x_for_train = torch.tensor(np.random.randn(10, 1024), device=device).type(dtype)
	y_for_train = torch.tensor(np.zeros(10), device=device).type(torch.LongTensor)

	x_for_train = x_for_train.type(dtype)

	opt.zero_grad()
	loss = cost(VQC = vqc, X = x_for_train, Y = y_for_train)
	loss.backward()
	opt.step()

if __name__ == '__main__':
	NUM_QUBITS = 10
	devices = [
	qml.device('default.qubit', wires = NUM_QUBITS),
	qml.device("qiskit.basicaer", wires=NUM_QUBITS),
	qml.device("qiskit.aer", wires=NUM_QUBITS),
	qml.device("forest.numpy_wavefunction", wires=NUM_QUBITS),
	qml.device("forest.wavefunction", wires=NUM_QUBITS),
	qml.device("forest.qvm", device="{}q-qvm".format(NUM_QUBITS)),
	qml.device("forest.qvm", device="{}q-pyqvm".format(NUM_QUBITS)),
	]

	for dev in devices:
		main(batch_size = 10, epoch_num = 100, dev = dev)


```

**Comment by josh146** [comment]
Hi @ycchen1989, thanks for this bug report! It looks like at some point the wire values are being passed to the `Rot` operations as a `np.int64` object, instead of a Python `int`. For the moment, this can be fixed with the following diff:

```diff
diff --git a/pennylane_forest/device.py b/pennylane_forest/device.py
index d49b5fd..b81f752 100644
--- a/pennylane_forest/device.py
+++ b/pennylane_forest/device.py
@@ -225,7 +225,7 @@ class ForestDevice(Device):

     def apply(self, operation, wires, par):
         # pylint: disable=attribute-defined-outside-init
-        self.prog += self._operation_map[operation](*par, *wires)
+        self.prog += self._operation_map[operation](*par, *[int(w) for w in wires])

         # keep track of the active wires. This is required, as the
         # pyQuil wavefunction simulator creates qubits dynamically.
```

I'll create a PR to fix this.
